spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

message:
  valid-window-in-seconds: 600